"use client";

import { Analytics } from "@vercel/analytics/react";

import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { SearchProvider } from "@/context/search";

import "./globals.scss";
import "react-tippy/dist/tippy.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Regulark</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <SearchProvider>
          <main className="layout_container">
            <Header />
            {children}
            <Analytics />
            <Footer />
          </main>
        </SearchProvider>
      </body>
    </html>
  );
}
